apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  selector:
    app: myapp
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-svc-demo
spec:
  replicas: 2
  selector:
    matchLabels:
        app: myapp
  template:
    metadata:
      name: headless-svc-demo
      labels:
        app: myapp
    spec:
      containers:
       - name: alpine
         image: nicolaka/netshoot
         command: ["/bin/bash", "-c", "sleep 3600"]
