apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "testuser" to read pods in the "kube-system" namespace.
kind: ClusterRoleBinding
metadata:
  name: prod-user-view-binding
  namespace: prod
subjects:
- kind: User 
  name: prod-user # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: view # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
