apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    tier: frontend
spec:
  containers:
  - name: hello1
    image: ubuntu
    command: ['/bin/bash', '-c', 'sleep 3600']

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    tier: frontend
spec:
  containers:
  - name: hello2
    image: alpine
    command: ['sh', '-c', 'sleep 1800']