apiVersion: v1
kind: Namespace
metadata:
  name: teama
  labels:
    name: development
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-demo
  namespace: teama
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
