apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
       app: myapp
  template:
    metadata:
       labels:
          app: myapp 
    spec:
      containers:
       - name: db
         image: mysql
         env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
         resources:
           requests:
             memory: "64Mi"
             cpu: "250m"
           limits:
             memory: "128Mi"
             cpu: "500m"
