apiVersion: v1
kind: Secret
metadata:
  name: secret2
type: Opaque
data:
  username: ZXhhbXBsZS11c2Vy
  password: ZXhhbXBsZS1wYXNzd29yZA==

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: secret2                #Name of secret
            key: username             #secret key
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret2
            key: password
  restartPolicy: Never
