apiVersion: v1
kind: Pod
metadata:
  name: high-priority-nginx2
  labels:
    env: test
spec:
  containers:
  - name: nginx-high-priority
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: high-priority

