apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
     type: monitoring

---

apiVersion: apps/v1
kind: Deployment
metadata:
   name: grafana
   labels:
      app: grafana-ui
   namespace: monitoring
spec:
  replicas: 1
  selector:
     matchLabels: 
       app: grafana-ui
  template:
     metadata:
       name: grafana
       labels:
          app: grafana-ui
     spec:
       containers:
         - name: grafana
           image: lerndevops/grafana
           ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
   name: grafana-ui-svc
   labels:
     app: grafana-ui
   namespace: monitoring 
spec:
  type: NodePort
  selector:
     app: grafana-ui
  ports:
    - port: 3000
      protocol: TCP
