apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: namespace1
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: namespace2
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: namespace3
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: namespace4
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
  namespace: namespace1
spec:
  containers:
  - image: nginx
    name: pod1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod2
  name: pod2
  namespace: namespace2
spec:
  containers:
  - image: ngnx
    name: pod2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod3
  name: pod3
  namespace: namespace3
spec:
  containers:
  - image: nginx
    name: pod3
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod4
  name: pod4
  namespace: namespace4
spec:
  containers:
  - image: nginx
    name: pod4
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
