apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels: 
     app: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat
    ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
     app: nginx
spec:
  containers:
  - name: nginx 
    image: nginx
    ports:
     - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
     app: nettools
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sh", "-c", "sleep 3600"] 

---

apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
     app: alpine
spec:
  containers:
  - name: alpine
    image: lerndevops/alpine:latest
    command: ["sh", "-c", "sleep 3600"]
