---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 80
    targetPort: 27017
    name: db
  clusterIP: None
  selector:
    app: db
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: "nginx"
  selector:
    matchLabels:
      app: db
  replicas: 8
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: cont1
        image: mongo
        ports:
        - containerPort: 27017
          name: web
        volumeMounts:
        - name: mongodb
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes:
         - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: azurefile
